services:
  tsflow:
    build: .
    ports:
      - "8080:8080"  # Backend serves both API and frontend
    environment:
      - TAILSCALE_API_KEY=${TAILSCALE_API_KEY}
      - TAILSCALE_TAILNET=${TAILSCALE_TAILNET}
      - PORT=8080
      - ENVIRONMENT=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount config if you want persistent settings
      - tsflow_data:/app/data
    networks:
      - tsflow

volumes:
  tsflow_data:

networks:
  tsflow:
    driver: bridge