services:
  tsflow:
    build: .
    ports:
      - "8080:8080"  # Backend serves both API and frontend
    environment:
      - TAILSCALE_API_KEY=${TAILSCALE_API_KEY}
      - TAILSCALE_TAILNET=${TAILSCALE_TAILNET}
      - PORT=8080
      - ENVIRONMENT=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - tsflow_data:/app/data
    networks:
      - tsflow

volumes:
  tsflow_data:

networks:
  tsflow:
    driver: bridge