version: '3.8'

services:
  tsflow:
    build: .
    ports:
      - "3000:3000"  # Frontend only
    environment:
      - VITE_TAILSCALE_API_KEY=${VITE_TAILSCALE_API_KEY}
      - VITE_TAILSCALE_TAILNET=${VITE_TAILSCALE_TAILNET}
      - VITE_TAILSCALE_BASE_URL=https://api.tailscale.com/api/v2
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount config if you want persistent settings
      - tsflow_data:/app/data
    networks:
      - tsflow

volumes:
  tsflow_data:

networks:
  tsflow:
    driver: bridge