version: '3.8'

services:
  tsflow:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TAILSCALE_ACCESS_TOKEN=${TAILSCALE_ACCESS_TOKEN}
      - TAILSCALE_TAILNET=${TAILSCALE_TAILNET}
    restart: unless-stopped